# Generated by Django 3.0.7 on 2020-09-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productMaster', '0002_auto_20200611_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_owner', models.CharField(max_length=255, verbose_name='Business Owner')),
            ],
        ),
        migrations.CreateModel(
            name='ListingMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('tgid', models.IntegerField()),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('tid', models.IntegerField()),
                ('variant_name', models.CharField(max_length=20, verbose_name='Variant Name')),
                ('listing_type', models.CharField(choices=[('null', '---'), ('Existing EC Update', 'Existing EC Update'), ('New EC Launch', 'New EC Launch'), ('Category Revamp', 'Category Revamp')], default='null', max_length=25)),
                ('frame_work_url', models.URLField(max_length=100, verbose_name='Frame Work Sheet URL')),
                ('trello_link', models.URLField(max_length=100, verbose_name='Trello Link')),
                ('urgency', models.CharField(choices=[('null', '---'), ('Urgent', 'Urgent (Within 1 working day)'), ('High', 'High (Within 2 working days)'), ('Medium', 'Medium (Within 4 working days)'), ('Low', 'Low (Within 6 working days)')], default='null', max_length=50)),
                ('listing_issue', models.CharField(choices=[('null', '---'), ('SP On-boarding Pending', 'SP On-boarding Pending'), ('SP Automation Pending', 'SP Automation Pending'), ('Product Link not working', 'Product Link not working')], default='null', max_length=25)),
                ('listing_status', models.CharField(choices=[('null', '---'), ('Live and Audited', 'Live and Audited'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked')], default='null', max_length=25)),
                ('Comments', models.TextField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('listing_poc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_members', to='productMaster.ListingMember')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='businessowner',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productMaster.Product'),
        ),
    ]
