# Generated by Django 3.0.7 on 2020-10-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMaster', '0003_auto_20200920_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_field',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
